echo "/*\n    Auto-generated by syms.sh." > syms.gen
echo "    DO NOT EDIT\n*/\n\n" >> syms.gen
echo "#include <stdint.h>\ntypedef struct { uint64_t addr; char* name; } symbol;" >> syms.gen
echo "const symbol __kernel_symtab[] = {" >> syms.gen
nm $1 | grep -i " t " | awk '{ print "    { .addr = 0x"$1", .name = \""$3"\" }," }' | sort >> syms.gen
echo "    { .addr = 0xffffffffffffffff, .name = \"\" }\n};" >> syms.gen
echo "    const uint64_t __kernel_symtab_size = sizeof(__kernel_symtab);" >> syms.gen