echo "/*\n    Auto-generated by syms.sh." > $2
echo "    DO NOT EDIT\n*/\n\n" >> $2
echo "#include <stdint.h>\ntypedef struct { uint64_t addr; char* name; } symbol;" >> $2
echo "const symbol __kernel_symtab[] = {" >> $2
nm $1 | grep -i " t " | awk '{ print "    { .addr = 0x"$1", .name = (char*) \""$3"\" }," }' | sort >> $2
echo "    { .addr = 0xffffffffffffffff, .name = (char*) \"\" }\n};" >> $2
echo "const uint64_t __kernel_symtab_size = sizeof(__kernel_symtab);" >> $2