name: Build the kernel documentation and deploy it to GitHub Pages

on:
  push:
    branches: [ main, docs ]
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build the kernel documentation
        run: |
          rm -rvf doc
          make -C src doc WEBPATH=/FoxOS-kernel

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/

      - name: Send request to server
        run: curl -X POST -F 'secret=${{ secrets.PHP_UPDATE_SECRET }}' -F 'updatedocs=true' https://theultimatefoxos.dev/kerneldoc-update.php
